# This is an example settings file for the JForum importer.

database:
  type: MySQL # currently only MySQL is supported
  host: localhost
  port: 3306
  username: root
  password:
  schema: jforum
  table_prefix: jforum_ # Change this, if your forum is using a different prefix. Usually all table names start with phpbb_
  batch_size: 1000 # Don't change this unless you know what you're doing. The default (1000) should work just fine.

import:
  # Enable this option if you want to have a better conversion of BBCodes to Markdown.
  # WARNING: This can slow down your import.
  use_bbcode_to_md: true

  # This is the path to the root directory of your current JForum installation (or a copy of it).
  # The importer expects to find the /files and /images directories within the base directory.
  # You need to change this to something like /var/lib/tomcat8/webapps/jforum/ if you are not using the Docker based importer.
  # This is only needed if you want to import avatars, attachments or custom smilies.
  jforum_base_dir: /Users/morn/Sources/jforum-migration/webapp/

  site_prefix:
    # this is needed for rewriting internal links in posts
    original: forum.verunsicherung.de/   # without http(s)://
    new: https://forum.verunsicherung.de       # with http:// or https://

  # Enable this, if you want to redirect old forum links to the the new locations.
  permalinks:
    categories: true  # redirects   /forums/show/123.page         to  /c/category-name
    topics: true      # redirects   /posts/list/234.page          to  /t/topic-name/81
    posts: true       # redirects   /posts/list/234.page#288      to  /t/topic-name/81 (couldn't map post directly)

  avatars:
    uploaded: true  # import uploaded avatars
    gallery: true   # import the predefined avatars phpBB offers
    remote: true   # WARNING: This can considerably slow down your import. It will try to download remote avatars.

  # Enable this, if you want import password hashes in order to use the "migratepassword" plugin.
  # This will allow users to login with their current password.
  # The plugin is available at: https://github.com/discoursehosting/discourse-migratepassword
  passwords: true

  # By default all the following things get imported. You can disable them by setting them to false.
  bookmarks: true
  attachments: true
  private_messages: true
  polls: true

  # When true: each imported user will have the original username from phpBB as its name
  # When false: the name of each imported user will be blank unless the username was changed during import
  username_as_name: false

  # Map Emojis to smilies used in JForum. Most of the default smilies already have a mapping, but you can override
  # the mappings here, if you don't like some of them.
  # The mapping syntax is: emoji_name: 'smiley_in_jforum'
  # Or map multiple smilies to one Emoji: emoji_name: ['smiley1', 'smiley2']
  emojis:
    # here are two example mappings...
    #smiley: [':D', ':-D', ':grin:']
    #heart: ':love:'
